In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones (10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(1)

array([0.46055107])

In [11]:
np.random.randn(25)

array([-0.11351636, -0.41073679, -0.61281901, -2.03434186, -0.58083451,
       -0.08193483, -0.15694359, -2.0900407 , -0.98144262, -0.1457774 ,
       -0.74073152,  2.44377193,  1.06006235, -0.15063334,  0.79576373,
        0.33312369,  0.34743596,  0.12784359, -1.03503782,  1.25779817,
       -1.80117489, -0.46170581,  1.76682931,  0.16936297,  0.78992196])

In [12]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
a=np.arange(1,26).reshape(5,5)

In [15]:
import numpy as np
a = np.arange(1,26).reshape(5,5)
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [18]:
a[3:4,4]

array([20])

In [19]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
a[4]

array([21, 22, 23, 24, 25])

In [21]:
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
a.sum()

325

In [23]:
a.std()

7.211102550927978

In [24]:
sum(a)

array([55, 60, 65, 70, 75])

In [25]:
a.sum(axis=0)
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [26]:
b = np.arange(16)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

d=np.arange(1,13).reshape(3,2,2)
d

In [28]:
b.dtype

dtype('int32')

In [29]:
c.dtype

dtype('int32')

In [30]:
c.dtype

dtype('int32')

In [31]:
b.shape

(16,)

In [32]:
c.shape

(4, 4)

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(16).reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
maths_marks=np.random.randint(1,100,20)
maths_marks

array([40, 14, 15, 87, 56, 35, 53, 58, 20, 81, 43,  6, 86,  9, 24, 61, 88,
       30, 48,  6])

In [36]:
ds=np.sort(maths_marks)
ds

array([ 6,  6,  9, 14, 15, 20, 24, 30, 35, 40, 43, 48, 53, 56, 58, 61, 81,
       86, 87, 88])

In [37]:
dsc=np.flip(ds)
dsc


array([88, 87, 86, 81, 61, 58, 56, 53, 48, 43, 40, 35, 30, 24, 20, 15, 14,
        9,  6,  6])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [40]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
x=mat
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.split?

In [44]:

np.split(x,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [45]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.split(x,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [47]:
np.split(mat,3,axis=1)


[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [48]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.split(v,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [50]:
np.random.uniform?

In [51]:
s=np.random.uniform(1,9,10)
s

array([7.34333244, 1.61304351, 1.95536422, 7.59305868, 4.17310986,
       1.36756151, 4.27001694, 2.7622646 , 8.99541478, 7.36368092])

In [52]:
np.ceil(s)

array([8., 2., 2., 8., 5., 2., 5., 3., 9., 8.])

In [53]:
np.floor(s)

array([7., 1., 1., 7., 4., 1., 4., 2., 8., 7.])

In [54]:
np.round(s,2)

array([7.34, 1.61, 1.96, 7.59, 4.17, 1.37, 4.27, 2.76, 9.  , 7.36])

In [55]:
q=np.arange(0,25).reshape(5,5)
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
q.min(axis=0)

array([0, 1, 2, 3, 4])

In [57]:
q.max(axis=0)

array([20, 21, 22, 23, 24])

In [58]:
q.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [59]:
q.var(axis=0)

array([50., 50., 50., 50., 50.])

In [60]:
dk=np.arange(100,151)
dk

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [61]:
np.flip(dk)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [62]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
m=np.ones((10,10))
m[1:-1,1:-1]=0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
n=np.zeros((8,8),dtype=int)
n[::2,::2] = 1
n[1::2,1::2]=1
n

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [65]:
s = np.random.randint(1,10,(3,3))
k =  np.random.randint(1,10,(3,3))

In [66]:
s+k

array([[15,  7,  6],
       [11,  8, 16],
       [ 2,  8,  9]])

In [67]:
s-k

array([[ 3, -1,  2],
       [ 5,  2,  0],
       [ 0,  0,  3]])

In [68]:
s*k

array([[54, 12,  8],
       [24, 15, 64],
       [ 1, 16, 18]])

In [69]:
import numpy as np
f=np.arange(20,29).reshape(3,3)
f
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
#create a 5*5 matrix of random interger value ranging from(0-50)
#shape dimension size of matrix
#return index of non zero element 
# assign all broders of these matrix as nan

In [71]:
import numpy as np

In [72]:
v=np.linspace(0,50,25).reshape(5,5)
v

array([[ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333],
       [10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ],
       [20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667],
       [31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333],
       [41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ]])

In [73]:
v.shape

(5, 5)

In [74]:
v.ndim

2

In [75]:
np.nonzero(v)


(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4], dtype=int64))

In [76]:
np.random.randn(0,1)

array([], shape=(0, 1), dtype=float64)